openapi: 3.0.0
servers: []
info:
  description: This API provides db info
  version: "1.0.0"
  title: Storage API
  contact:
    email: syousefi1@my.bcit.ca
tags:
  - name: customers
    description: operations available for customers to request


paths:
  /requests/immediate-ride:
    get:
      tags:
        - devices
      summary: gets new ride request readings
      operationId: app.get_ride_request_readings
      description: Gets ride request readings added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
      responses:
        '200':
          description: Successfully returned a list of ride request events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RideRequest'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
    post:
      tags:
        - customers
      summary: receives a new request from the customer
      operationId: app.immediate_ride
      description: Adds an immediate ride from a customer to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RideRequest'
        description: requested item to add

  /requests/schedule-ride:
    get:
      tags:
        - devices
      summary: gets new schedule ride request readings
      operationId: app.get_schedule_request_readings
      description: Gets schedule request readings added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
        - name: end_timestamp
          in: query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: '2016-08-29 09:12:33'
      responses:
        '200':
          description: Successfully returned a list of schedule request events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleRequest'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    post:
      tags:
        - customers
      summary: notifies a new scheduled request from the customers
      operationId: app.scheduled_ride
      description: Adds an scheduled ride from a customer to the system
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleRequest'
        description: requested item to add


components:
  schemas:

    RideRequest:
      type: object
      required:
        - customer_id
        - distance
        - price
        - payment_method_id
        - trace_id
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        distance:
          type: number
          example: 6.5
        price:
          type: number
          example: 15.75
        payment_method_id:
          type: string
          example: A12345
        trace_id:
          type: string
          format: uuid
          example: fbd204a7-318e-4dd3-86e0-e6d524fc3f98

    ScheduleRequest:
      type: object
      required:
        - customer_id
        - date_time
        - distance
        - price
        - trace_id
      properties:
        customer_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        date_time:
          type: string
          format: date-time
          example: '2016-08-29 09:12:33'
        distance:
          type: number
          example: 6.5
        price:
          type: number
          example: 15.75
        trace_id:
          type: string
          format: uuid
          example: fbd204a7-318e-4dd3-86e0-e6d524fc3f98
